# Generated by Django 3.1 on 2020-09-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messege',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='subject',
        ),
    ]
